<?php

function basket_convocation_mail($key, &$message, $params) {
    switch($key) {
        case 'convocation':
            $message['subject'] = t('Convocation au match : @matchTitle', array('@matchTitle' => $params['match_title']));
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['body'][] =
                t('Bonjour,')."<br><br>".
                t('Tu reçois ce mail car tu es convoqué pour le match : ')."<br>".
                $params['match_title']."<br>".
                $params['match_domext']."<br>".
                t('le @date à @heure', array('@date' => date('d/m/Y', $params['match_date']), '@heure' => date('H:i', $params['match_date'])))."<br><br>".
				t('Pour avoir plus d\'informations sur le match (date et heure du rendez-vous, adresse de la salle...), tu peux aller <a href="@matchUrl">ici</a>.', array('@matchUrl' => $params['match_url']))."<br><br>".
				t('A bientôt,')."<br>".
                $params['user_name'];
            break;
    }
}

function basket_convocation_preprocess_node(&$variables) {
    $node = $variables['node'];
    if ($node->bundle() == 'matchs') {
        $variables['show_convocation_link'] = FALSE;
        if (\Drupal::currentUser()->hasPermission('do convocation')) {
            $variables['show_convocation_link'] = true;
        }
        
        // Mise en place de l'adresse pour utiliser google map
        if ($node->field_adresse_gymnase) {
            $adresseInfos = $node->field_adresse_gymnase->get(0)->getValue();
            $gmapAdr = [
                $adresseInfos['address_line1'],
                $adresseInfos['address_line2'],
                $adresseInfos['postal_code'],
                $adresseInfos['locality'],
                $adresseInfos['country_code'],
            ];
            
            $variables['gmap_address'] = urlencode(implode(', ', $gmapAdr));
        }
    }
}

function basket_convocation_preprocess_field(&$variables) {
    if ($variables['field_name'] == 'field_adresse_gymnase') {
        $adr = $variables['items'][0]['content'];
        $gmapAdr = [
            $adr['address_line1']['#value'],
            $adr['address_line2']['#value'],
            $adr['postal_code']['#value'],
            $adr['locality']['#value'],
            $adr['country_code']['#value'],
        ];
        $variables['gmap_address'] = urlencode(implode(', ', $gmapAdr));
    }
}